#!/bin/bash
if [ ! -f "$1" ]; then
	echo "need file as parameter"
	exit 1
fi
[ "$2" == "dumb" ] && DUMB="set terminal dumb; "
F="$1"
SEPVALS=$(grep "sep:[[:space:]]*value:" "$F" | sed -r 's/^.*sep:[[:space:]]*value: ([^,]*),.*$/\1/')
RAWVAL=$(grep "bid:[[:space:]]*revenue" "$F" | sed -r "s/^.*bid:[[:space:]]*revenue ([0-9]*).*$/\1/")
RAWVALS=$(echo "$SEPVALS" | sed "s/^.*$/$RAWVAL/")
{ 
	echo "$RAWVALS"; echo 'e';
	echo "$SEPVALS"; echo 'e';
	grep "ebpo:[[:space:]]*revenue:" "$F" | sed -r 's/^.*ebpo:[[:space:]]*revenue: //'; echo 'e';
	grep "sep:[[:space:]]*value_blocking_coalition:" "$F" | sed -r 's/^.*sep:[[:space:]]*value_blocking_coalition: ([^,]*),.*$/\1/'; echo 'e' 
} | gnuplot -p -e "set grid;$DUMB plot '-' using 1 with l, '' using 1 with l, '' using 1 with l, '' using 1 with l;"
